-- TC_SB_35
-- By: Santiago Balcero
-- Date: 2022-11-24
-- Description: creates schema APP_GEST_E_MASCOTAS

CREATE USER APP_GEST_E_MASCOTAS IDENTIFIED BY 1234 DEFAULT TABLESPACE TS_APP_GEST_E_MASCOTAS QUOTA UNLIMITED ON TS_APP_GEST_E_MASCOTAS;
