-- TC_SB_35
-- By: Santiago Balcero
-- Date: 2022-12-1
-- Description: creates FOREIGN KEY for column ID_DEPARTMENT in table CLINIC

ALTER TABLE APP_GEST_E_MASCOTAS.CLINIC ADD CONSTRAINT FK_CLINIC_ID_DEPARTMENT FOREIGN KEY (ID_DEPARTMENT) REFERENCES APP_GEST_E_MASCOTAS.DEPARTMENT (ID_DEPARTMENT);
