-- TC_SB_35
-- By: Santiago Balcero
-- Date: 2022-12-2
-- Description: creates FOREIGN KEY for column ID_CLINIC in table EMERGENCY

ALTER TABLE APP_GEST_E_MASCOTAS.EMERGENCY ADD CONSTRAINT FK_EMERGENCY_ID_CLINIC FOREIGN KEY (ID_CLINIC) REFERENCES APP_GEST_E_MASCOTAS.CLINIC (ID_CLINIC);
