-- TC_SB_35
-- By: Santiago Balcero
-- Date: 2022-12-2
-- Description: creates FOREIGN KEY for column ID_SPECIES in table EMERGENCY

ALTER TABLE APP_GEST_E_MASCOTAS.EMERGENCY ADD CONSTRAINT FK_EMERGENCY_ID_SPECIES FOREIGN KEY (ID_SPECIES) REFERENCES APP_GEST_E_MASCOTAS.SPECIES (ID_SPECIES);
