-- TC_SB_35
-- By: Santiago Balcero
-- Date: 2022-12-2
-- Description: creates FOREIGN KEY for column ID_CLIENT in table SUBSCRIPTION

ALTER TABLE APP_GEST_E_MASCOTAS.SUBSCRIPTION ADD CONSTRAINT FK_SUBSCRIPTION_ID_CLIENT FOREIGN KEY (ID_CLIENT) REFERENCES APP_GEST_E_MASCOTAS.CLIENT (ID_CLIENT);
