-- TC_SB_35
-- By: Santiago Balcero
-- Date: 2022-12-3
-- Description: creates constraint UNIQUE for column ID_CLIENT in table SUBSCRIPTION

ALTER TABLE APP_GEST_E_MASCOTAS.SUBSCRIPTION ADD CONSTRAINT UQ_SUBSCRIPTION_ID_CLIENT UNIQUE (ID_CLIENT);
