-- TC_SB_35
-- By: Santiago Balcero
-- Date: 2022-12-1
-- Description: creates constraint UNIQUE for column VET_DOCUMENT in table VETERINARIAN

ALTER TABLE APP_GEST_E_MASCOTAS.VETERINARIAN ADD CONSTRAINT UQ_VET_DOCUMENT UNIQUE (VET_DOCUMENT);
