-- TC_SB_35
-- By: Santiago Balcero
-- Date: 2022-12-2
-- Description: creates INDEX for column ID_SUBSCRIPTION in table EMERGENCY

CREATE INDEX IX_EMERGENCY_ID_SUBSCRIPTION ON APP_GEST_E_MASCOTAS.EMERGENCY (ID_SUBSCRIPTION);
