-- TC_SB_35
-- By: Santiago Balcero
-- Date: 2022-12-1
-- Description: creates composite PRIMARY KEY for join table CLINIC_SERVICE

ALTER TABLE APP_GEST_E_MASCOTAS.CLINIC_SERVICE ADD CONSTRAINT PK_CLINIC_SERVICE PRIMARY KEY (MIX_ID_CLINIC, MIX_ID_SERVICE);
