-- TC_SB_35
-- By: Santiago Balcero
-- Date: 2022-12-1
-- Description: creates PRIMARY KEY for table DEPARTMENT

ALTER TABLE APP_GEST_E_MASCOTAS.DEPARTMENT ADD CONSTRAINT PK_DEPARTMENT PRIMARY KEY (ID_DEPARTMENT);
