-- TC_SB_35
-- By: Santiago Balcero
-- Date: 2022-12-1
-- Description: creates PRIMARY KEY for table EMERGENCY

ALTER TABLE APP_GEST_E_MASCOTAS.EMERGENCY ADD CONSTRAINT PK_EMERGENCY PRIMARY KEY (ID_EMERGENCY);
