-- TC_SB_35
-- By: Santiago Balcero
-- Date: 2022-12-2
-- Description: creates PRIMARY KEY for table MAIN_SYMPTOM

ALTER TABLE APP_GEST_E_MASCOTAS.MAIN_SYMPTOM ADD CONSTRAINT PK_MAIN_SYMPTOM PRIMARY KEY (ID_MAIN_SYMPTOM);
