-- TC_SB_35
-- By: Santiago Balcero
-- Date: 2022-12-2
-- Description: creates PRIMARY KEY for table SPECIES

ALTER TABLE APP_GEST_E_MASCOTAS.SPECIES ADD CONSTRAINT PK_SPECIES PRIMARY KEY (ID_SPECIES);
