-- TC_SB_35
-- By: Santiago Balcero
-- Date: 2022-12-2
-- Description: creates PRIMARY KEY for table SUBSCRIPTION

ALTER TABLE APP_GEST_E_MASCOTAS.SUBSCRIPTION ADD CONSTRAINT PK_SUBSCRIPTION PRIMARY KEY (ID_SUBSCRIPTION);
