-- TC_SB_35
-- By: Santiago Balcero
-- Date: 2022-12-1
-- Description: creates PRIMARY KEY for table SERVICE

ALTER TABLE APP_GEST_E_MASCOTAS.SERVICE ADD CONSTRAINT PK_SERVICE PRIMARY KEY (ID_SERVICE);
