-- TC_SB_35
-- By: Santiago Balcero
-- Date: 2022-12-1
-- Description: creates PRIMARY KEY for table VETERINARIAN

ALTER TABLE APP_GEST_E_MASCOTAS.VETERINARIAN ADD CONSTRAINT PK_VETERINARIAN PRIMARY KEY (ID_VETERINARIAN);
