-- TC_SB_35
-- By: Santiago Balcero
-- Date: 2022-12-1
-- Description: creates table CLIENT for clients that may have subscription to emergency services

CREATE TABLE APP_GEST_E_MASCOTAS.CLIENT (
    ID_CLIENT NUMBER NOT NULL,
    CLIENT_DOCUMENT VARCHAR2(20) NOT NULL,
    CLIENT_NAME VARCHAR2(50) NOT NULL,
    CLIENT_LASTNAME VARCHAR2(50) NOT NULL,
    CLIENT_TELEPHONE VARCHAR2(12) NOT NULL,
    CLIENT_EMAIL VARCHAR2(50) NOT NULL,
    CLIENT_PASSWORD VARCHAR2(64) NOT NULL,
    IS_ACTIVE NUMBER NOT NULL,
    LAST_UPDATE_DATE DATE NOT NULL,
    LAST_UPDATE_ACTION VARCHAR2(20) NOT NULL
);

COMMENT ON TABLE APP_GEST_E_MASCOTAS.CLIENT IS 'LIST OF CLIENTS THAT MAY HAVE SUBSCRIPTION TO EMERGENCY SERVICES';
