-- TC_SB_35
-- By: Santiago Balcero
-- Date: 2022-11-24
-- Description: creates table CLINIC for clinics with agreement for emergency services

CREATE TABLE APP_GEST_E_MASCOTAS.CLINIC (
    ID_CLINIC NUMBER NOT NULL,
    CLINIC_NAME VARCHAR2(50) NOT NULL,
    CLINIC_NIT VARCHAR2(9) NOT NULL,
    ID_DEPARTMENT NUMBER NOT NULL,
    CLINIC_CITY VARCHAR2(40) NOT NULL,
    CLINIC_ADDRESS VARCHAR2(50) NOT NULL,
    CLINIC_LATITUDE NUMBER NOT NULL,
    CLINIC_LONGITUDE NUMBER NOT NULL,
    CLINIC_TELEPHONE VARCHAR2(12) NOT NULL,
    CLINIC_EMAIL VARCHAR2(50) NOT NULL,
    IS_ACTIVE NUMBER NOT NULL,
    LAST_UPDATE_DATE DATE NOT NULL,
    LAST_UPDATE_ACTION VARCHAR2(20) NOT NULL
);

COMMENT ON TABLE APP_GEST_E_MASCOTAS.CLINIC IS 'LIST OF CLINICS WITH AGREEMENT FOR EMERGENCY SERVICES';
