-- TC_SB_35
-- By: Santiago Balcero
-- Date: 2022-11-24
-- Description: creates table DEPARTMENT for list of colombian departments

CREATE TABLE APP_GEST_E_MASCOTAS.DEPARTMENT (
    ID_DEPARTMENT NUMBER NOT NULL,
    DEPARTMENT VARCHAR2(25) NOT NULL
);

COMMENT ON TABLE APP_GEST_E_MASCOTAS.DEPARTMENT IS 'LIST OF COLOMBIAN DEPARTMENTS';
