-- TC_SB_35
-- By: Santiago Balcero
-- Date: 2022-12-2
-- Description: creates table EMERGENCY for emergencies that users with subscription want to be attended

CREATE TABLE APP_GEST_E_MASCOTAS.EMERGENCY (
    ID_EMERGENCY NUMBER NOT NULL,
    ID_SUBSCRIPTION NUMBER NOT NULL,
    ID_CLINIC NUMBER NOT NULL,
    EMERGENCY_DATE DATE NOT NULL,
    EMERGENCY_STATUS VARCHAR2(10) NOT NULL,
    ID_SPECIES NUMBER NOT NULL,
    ID_MAIN_SYMPTOM NUMBER NOT NULL,
    EMERGENCY_DESCRIPTION VARCHAR2(1000) NOT NULL,
    LAST_STATUS_UPDATE DATE NOT NULL
);

COMMENT ON TABLE APP_GEST_E_MASCOTAS.EMERGENCY IS 'LIST OF EMERGENCIES THAT USERS WITH SUBSCRIPTION WANT TO BE ATTENDED';
