-- TC_SB_35
-- By: Santiago Balcero
-- Date: 2022-12-2
-- Description: creates table MAIN_SYMPTOM for users to report symptom of their pets

CREATE TABLE APP_GEST_E_MASCOTAS.MAIN_SYMPTOM (
    ID_MAIN_SYMPTOM NUMBER NOT NULL,
    MAIN_SYMPTOM VARCHAR2(50) NOT NULL
);

COMMENT ON TABLE APP_GEST_E_MASCOTAS.MAIN_SYMPTOM IS 'LIST OF MAIN SYMPTOMS THAT USERS CAN REPORT FOR THEIR PETS';