-- TC_SB_35
-- By: Santiago Balcero
-- Date: 2022-12-15
-- Description: creates table REPORT for counting number of emergencies attended according 
-- to year, month, main symptom, species

CREATE TABLE APP_GEST_E_MASCOTAS.REPORT (
    ID_REPORT NUMBER NOT NULL,
    REPORT_YEAR NUMBER NOT NULL,
    REPORT_MONTH NUMBER NOT NULL,
    ID_SPECIES NUMBER NOT NULL,
    ID_MAIN_SYMPTOM NUMBER NOT NULL,
    NUMBER_EMERGENCIES NUMBER NOT NULL
    REPORT_EXECUTION_DATE DATE NOT NULL,
    EXECUTED_BY VARCHAR2(6) NOT NULL,
    FINISH_STATUS VARCHAR2(20) NOT NULL
);

COMMENT ON TABLE APP_GEST_E_MASCOTAS.REPORT IS 'LIST OF REPORTS CONSISTING OF NUMBER OF EMERGENCIES WITH STATUS CONFIRMED FOR EVERY MONTH, YEAR, SPECIES, SYMPTOM';