-- TC_SB_35
-- By: Santiago Balcero
-- Date: 2022-11-24
-- Description: creates table VETERINARIAN for veterinarians that work in the clinics part of the agreement

CREATE TABLE APP_GEST_E_MASCOTAS.VETERINARIAN (
    ID_VETERINARIAN NUMBER NOT NULL,
    VET_DOCUMENT VARCHAR2(20) NOT NULL,
    ID_CLINIC NUMBER NOT NULL,
    VET_NAME VARCHAR2(50) NOT NULL,
    VET_LASTNAME VARCHAR2(50) NOT NULL,
    VET_TELEPHONE VARCHAR2(12) NOT NULL,
    VET_EMAIL VARCHAR2(50) NOT NULL,
    IS_ACTIVE NUMBER NOT NULL,
    LAST_UPDATE_DATE DATE NOT NULL,
    LAST_UPDATE_ACTION VARCHAR2(20)
);

COMMENT ON TABLE APP_GEST_E_MASCOTAS.VETERINARIAN IS 'LIST OF VETERINARIANS THAT WORK IN THE CLINICS PART OF THE AGREEMENT';
