-- TC_SB_35
-- By: Santiago Balcero
-- Date: 2022-12-2
-- Description: inserts species that clients may own into table SPECIES 

INSERT INTO APP_GEST_E_MASCOTAS.SPECIES (ID_SPECIES, SPECIES) VALUES (SEQ_SPECIES.NEXTVAL, 'Perro');
INSERT INTO APP_GEST_E_MASCOTAS.SPECIES (ID_SPECIES, SPECIES) VALUES (SEQ_SPECIES.NEXTVAL, 'Gato');
INSERT INTO APP_GEST_E_MASCOTAS.SPECIES (ID_SPECIES, SPECIES) VALUES (SEQ_SPECIES.NEXTVAL, 'Ave');
INSERT INTO APP_GEST_E_MASCOTAS.SPECIES (ID_SPECIES, SPECIES) VALUES (SEQ_SPECIES.NEXTVAL, 'Pez');
INSERT INTO APP_GEST_E_MASCOTAS.SPECIES (ID_SPECIES, SPECIES) VALUES (SEQ_SPECIES.NEXTVAL, 'Cerdo');
INSERT INTO APP_GEST_E_MASCOTAS.SPECIES (ID_SPECIES, SPECIES) VALUES (SEQ_SPECIES.NEXTVAL, 'Roedor');
INSERT INTO APP_GEST_E_MASCOTAS.SPECIES (ID_SPECIES, SPECIES) VALUES (SEQ_SPECIES.NEXTVAL, 'Conejo');
INSERT INTO APP_GEST_E_MASCOTAS.SPECIES (ID_SPECIES, SPECIES) VALUES (SEQ_SPECIES.NEXTVAL, 'Caballo');
INSERT INTO APP_GEST_E_MASCOTAS.SPECIES (ID_SPECIES, SPECIES) VALUES (SEQ_SPECIES.NEXTVAL, 'Otro');
COMMIT;
/