-- TC_SB_35
-- By: Santiago Balcero
-- Date: 2022-11-25
-- Description: inserts services offered by clinics into table SERVICE

INSERT INTO APP_GEST_E_MASCOTAS.SERVICE (ID_SERVICE, SERVICE) VALUES (SEQ_SERVICE.NEXTVAL, 'Urgencias');
INSERT INTO APP_GEST_E_MASCOTAS.SERVICE (ID_SERVICE, SERVICE) VALUES (SEQ_SERVICE.NEXTVAL, 'Medicina externa');
INSERT INTO APP_GEST_E_MASCOTAS.SERVICE (ID_SERVICE, SERVICE) VALUES (SEQ_SERVICE.NEXTVAL, 'Cirugía');
INSERT INTO APP_GEST_E_MASCOTAS.SERVICE (ID_SERVICE, SERVICE) VALUES (SEQ_SERVICE.NEXTVAL, 'Hospitalización');
INSERT INTO APP_GEST_E_MASCOTAS.SERVICE (ID_SERVICE, SERVICE) VALUES (SEQ_SERVICE.NEXTVAL, 'Imágenes diagnósticas');
INSERT INTO APP_GEST_E_MASCOTAS.SERVICE (ID_SERVICE, SERVICE) VALUES (SEQ_SERVICE.NEXTVAL, 'Laboratorio clínico');
INSERT INTO APP_GEST_E_MASCOTAS.SERVICE (ID_SERVICE, SERVICE) VALUES (SEQ_SERVICE.NEXTVAL, 'Ortopedia');
INSERT INTO APP_GEST_E_MASCOTAS.SERVICE (ID_SERVICE, SERVICE) VALUES (SEQ_SERVICE.NEXTVAL, 'Cardiología');
INSERT INTO APP_GEST_E_MASCOTAS.SERVICE (ID_SERVICE, SERVICE) VALUES (SEQ_SERVICE.NEXTVAL, 'Oncología');
INSERT INTO APP_GEST_E_MASCOTAS.SERVICE (ID_SERVICE, SERVICE) VALUES (SEQ_SERVICE.NEXTVAL, 'Oftalmología');
INSERT INTO APP_GEST_E_MASCOTAS.SERVICE (ID_SERVICE, SERVICE) VALUES (SEQ_SERVICE.NEXTVAL, 'Dermatología');
INSERT INTO APP_GEST_E_MASCOTAS.SERVICE (ID_SERVICE, SERVICE) VALUES (SEQ_SERVICE.NEXTVAL, 'Estética');
INSERT INTO APP_GEST_E_MASCOTAS.SERVICE (ID_SERVICE, SERVICE) VALUES (SEQ_SERVICE.NEXTVAL, 'Guardería');
COMMIT;
/