-- TC_SB_35
-- By: Santiago Balcero
-- Date: 2022-11-24
-- Description: inserts colombian departments into table DEPARTMENT

INSERT INTO APP_GEST_E_MASCOTAS.DEPARTMENT (ID_DEPARTMENT, DEPARTMENT) VALUES (SEQ_DEPARTMENT.NEXTVAL, 'Amazonas');
INSERT INTO APP_GEST_E_MASCOTAS.DEPARTMENT (ID_DEPARTMENT, DEPARTMENT) VALUES (SEQ_DEPARTMENT.NEXTVAL, 'Antioquia');
INSERT INTO APP_GEST_E_MASCOTAS.DEPARTMENT (ID_DEPARTMENT, DEPARTMENT) VALUES (SEQ_DEPARTMENT.NEXTVAL, 'Arauca');
INSERT INTO APP_GEST_E_MASCOTAS.DEPARTMENT (ID_DEPARTMENT, DEPARTMENT) VALUES (SEQ_DEPARTMENT.NEXTVAL, 'Atlántico');
INSERT INTO APP_GEST_E_MASCOTAS.DEPARTMENT (ID_DEPARTMENT, DEPARTMENT) VALUES (SEQ_DEPARTMENT.NEXTVAL, 'Bogotá D.C.');
INSERT INTO APP_GEST_E_MASCOTAS.DEPARTMENT (ID_DEPARTMENT, DEPARTMENT) VALUES (SEQ_DEPARTMENT.NEXTVAL, 'Bolívar');
INSERT INTO APP_GEST_E_MASCOTAS.DEPARTMENT (ID_DEPARTMENT, DEPARTMENT) VALUES (SEQ_DEPARTMENT.NEXTVAL, 'Boyacá');
INSERT INTO APP_GEST_E_MASCOTAS.DEPARTMENT (ID_DEPARTMENT, DEPARTMENT) VALUES (SEQ_DEPARTMENT.NEXTVAL, 'Caldas');
INSERT INTO APP_GEST_E_MASCOTAS.DEPARTMENT (ID_DEPARTMENT, DEPARTMENT) VALUES (SEQ_DEPARTMENT.NEXTVAL, 'Caquetá');
INSERT INTO APP_GEST_E_MASCOTAS.DEPARTMENT (ID_DEPARTMENT, DEPARTMENT) VALUES (SEQ_DEPARTMENT.NEXTVAL, 'Casanare');
INSERT INTO APP_GEST_E_MASCOTAS.DEPARTMENT (ID_DEPARTMENT, DEPARTMENT) VALUES (SEQ_DEPARTMENT.NEXTVAL, 'Cauca');
INSERT INTO APP_GEST_E_MASCOTAS.DEPARTMENT (ID_DEPARTMENT, DEPARTMENT) VALUES (SEQ_DEPARTMENT.NEXTVAL, 'Cesar');
INSERT INTO APP_GEST_E_MASCOTAS.DEPARTMENT (ID_DEPARTMENT, DEPARTMENT) VALUES (SEQ_DEPARTMENT.NEXTVAL, 'Chocó');
INSERT INTO APP_GEST_E_MASCOTAS.DEPARTMENT (ID_DEPARTMENT, DEPARTMENT) VALUES (SEQ_DEPARTMENT.NEXTVAL, 'Córdoba');
INSERT INTO APP_GEST_E_MASCOTAS.DEPARTMENT (ID_DEPARTMENT, DEPARTMENT) VALUES (SEQ_DEPARTMENT.NEXTVAL, 'Cundinamarca');
INSERT INTO APP_GEST_E_MASCOTAS.DEPARTMENT (ID_DEPARTMENT, DEPARTMENT) VALUES (SEQ_DEPARTMENT.NEXTVAL, 'Guainía');
INSERT INTO APP_GEST_E_MASCOTAS.DEPARTMENT (ID_DEPARTMENT, DEPARTMENT) VALUES (SEQ_DEPARTMENT.NEXTVAL, 'Guaviare');
INSERT INTO APP_GEST_E_MASCOTAS.DEPARTMENT (ID_DEPARTMENT, DEPARTMENT) VALUES (SEQ_DEPARTMENT.NEXTVAL, 'Huila');
INSERT INTO APP_GEST_E_MASCOTAS.DEPARTMENT (ID_DEPARTMENT, DEPARTMENT) VALUES (SEQ_DEPARTMENT.NEXTVAL, 'La Guajira');
INSERT INTO APP_GEST_E_MASCOTAS.DEPARTMENT (ID_DEPARTMENT, DEPARTMENT) VALUES (SEQ_DEPARTMENT.NEXTVAL, 'Magdalena');
INSERT INTO APP_GEST_E_MASCOTAS.DEPARTMENT (ID_DEPARTMENT, DEPARTMENT) VALUES (SEQ_DEPARTMENT.NEXTVAL, 'Meta');
INSERT INTO APP_GEST_E_MASCOTAS.DEPARTMENT (ID_DEPARTMENT, DEPARTMENT) VALUES (SEQ_DEPARTMENT.NEXTVAL, 'Nariño');
INSERT INTO APP_GEST_E_MASCOTAS.DEPARTMENT (ID_DEPARTMENT, DEPARTMENT) VALUES (SEQ_DEPARTMENT.NEXTVAL, 'Norte de Santander');
INSERT INTO APP_GEST_E_MASCOTAS.DEPARTMENT (ID_DEPARTMENT, DEPARTMENT) VALUES (SEQ_DEPARTMENT.NEXTVAL, 'Putumayo');
INSERT INTO APP_GEST_E_MASCOTAS.DEPARTMENT (ID_DEPARTMENT, DEPARTMENT) VALUES (SEQ_DEPARTMENT.NEXTVAL, 'Quindío');
INSERT INTO APP_GEST_E_MASCOTAS.DEPARTMENT (ID_DEPARTMENT, DEPARTMENT) VALUES (SEQ_DEPARTMENT.NEXTVAL, 'Risaralda');
INSERT INTO APP_GEST_E_MASCOTAS.DEPARTMENT (ID_DEPARTMENT, DEPARTMENT) VALUES (SEQ_DEPARTMENT.NEXTVAL, 'San Andrés y Providencia');
INSERT INTO APP_GEST_E_MASCOTAS.DEPARTMENT (ID_DEPARTMENT, DEPARTMENT) VALUES (SEQ_DEPARTMENT.NEXTVAL, 'Santander');
INSERT INTO APP_GEST_E_MASCOTAS.DEPARTMENT (ID_DEPARTMENT, DEPARTMENT) VALUES (SEQ_DEPARTMENT.NEXTVAL, 'Sucre');
INSERT INTO APP_GEST_E_MASCOTAS.DEPARTMENT (ID_DEPARTMENT, DEPARTMENT) VALUES (SEQ_DEPARTMENT.NEXTVAL, 'Tolima');
INSERT INTO APP_GEST_E_MASCOTAS.DEPARTMENT (ID_DEPARTMENT, DEPARTMENT) VALUES (SEQ_DEPARTMENT.NEXTVAL, 'Valle del Cauca');
INSERT INTO APP_GEST_E_MASCOTAS.DEPARTMENT (ID_DEPARTMENT, DEPARTMENT) VALUES (SEQ_DEPARTMENT.NEXTVAL, 'Vaupés');
INSERT INTO APP_GEST_E_MASCOTAS.DEPARTMENT (ID_DEPARTMENT, DEPARTMENT) VALUES (SEQ_DEPARTMENT.NEXTVAL, 'Vichada');
COMMIT;
/