-- TC_SB_35
-- By: Santiago Balcero
-- Date: 2022-12-2
-- Description: inserts main symptoms for users to choose into table MAIN_SYMPTOM

INSERT INTO APP_GEST_E_MASCOTAS.MAIN_SYMPTOM (ID_MAIN_SYMPTOM, MAIN_SYMPTOM) VALUES (SEQ_MAIN_SYMPTOM.NEXTVAL, 'Dificultad respiratoria');
INSERT INTO APP_GEST_E_MASCOTAS.MAIN_SYMPTOM (ID_MAIN_SYMPTOM, MAIN_SYMPTOM) VALUES (SEQ_MAIN_SYMPTOM.NEXTVAL, 'Traumatismo y/o fractura');
INSERT INTO APP_GEST_E_MASCOTAS.MAIN_SYMPTOM (ID_MAIN_SYMPTOM, MAIN_SYMPTOM) VALUES (SEQ_MAIN_SYMPTOM.NEXTVAL, 'Anormalidades neurológicas o depresión severa');
INSERT INTO APP_GEST_E_MASCOTAS.MAIN_SYMPTOM (ID_MAIN_SYMPTOM, MAIN_SYMPTOM) VALUES (SEQ_MAIN_SYMPTOM.NEXTVAL, 'Vómito o diarrea');
INSERT INTO APP_GEST_E_MASCOTAS.MAIN_SYMPTOM (ID_MAIN_SYMPTOM, MAIN_SYMPTOM) VALUES (SEQ_MAIN_SYMPTOM.NEXTVAL, 'Sangrado visible');
INSERT INTO APP_GEST_E_MASCOTAS.MAIN_SYMPTOM (ID_MAIN_SYMPTOM, MAIN_SYMPTOM) VALUES (SEQ_MAIN_SYMPTOM.NEXTVAL, 'Palidez de mucosas');
INSERT INTO APP_GEST_E_MASCOTAS.MAIN_SYMPTOM (ID_MAIN_SYMPTOM, MAIN_SYMPTOM) VALUES (SEQ_MAIN_SYMPTOM.NEXTVAL, 'Debilidad extrema o incapacidad para moverse');
INSERT INTO APP_GEST_E_MASCOTAS.MAIN_SYMPTOM (ID_MAIN_SYMPTOM, MAIN_SYMPTOM) VALUES (SEQ_MAIN_SYMPTOM.NEXTVAL, 'Incapacidad para orinar y/o defecar');
INSERT INTO APP_GEST_E_MASCOTAS.MAIN_SYMPTOM (ID_MAIN_SYMPTOM, MAIN_SYMPTOM) VALUES (SEQ_MAIN_SYMPTOM.NEXTVAL, 'Ingestión de toxinas o cuerpos extraños');
INSERT INTO APP_GEST_E_MASCOTAS.MAIN_SYMPTOM (ID_MAIN_SYMPTOM, MAIN_SYMPTOM) VALUES (SEQ_MAIN_SYMPTOM.NEXTVAL, 'Dolor severo');
INSERT INTO APP_GEST_E_MASCOTAS.MAIN_SYMPTOM (ID_MAIN_SYMPTOM, MAIN_SYMPTOM) VALUES (SEQ_MAIN_SYMPTOM.NEXTVAL, 'Otro');
COMMIT;
/